### ISSUE TITLE
Delivery shouldn't use the Bcc field for non-followers

### ISSUE THREAD

**Issue by MrPetovan** [gabboman/wafrn-backend#10]
See https://github.com/friendica/friendica/issues/13152

Friendica accepts messages targeting local users mentioned in the To, Cc or Bcc fields the same way as email. If a message isn't intended for specific accounts, they shouldn't be mentioned in these addressing fields.

**Comment by gabboman** [comment]
will fix soon thanks. will keep the issue open

**Comment by gabboman** [comment]
what field should I use is the correct question then? sorry, long day and brainrot @MrPetovan

**Comment by MrPetovan** [comment]
I'm not as knowledgeable about protocol stuff as @annando, maybe he can help you answer this question.

**Comment by annando** [comment]
For postings to followers you should simply put the follower as a receiver and should deliver to the shared inbox. This works for both private and public posts.

**Comment by gabboman** [comment]
@annando the issue is that the post is public  in the server. When I send the post to a server it is sent with the #public thingy [(lines 115 to 120 )](https://github.com/gabboman/wafrn-backend/blob/main/utils/activitypub/postToJSONLD.ts)

the concept is "hey everyone here is this post. put it on your explore tag"

am I wrong here or is friendica wrong?

**Comment by MrPetovan** [comment]
Since I'm not in your followers (no hard feelings), my account shouldn't be in the `cc` section and you shouldn't deliver to my Friendica node, so I believe there's something wrong with your implementation.

**Comment by gabboman** [comment]
The object I send to each instance is this:

[https://pastebin.com/DYWiqhek](https://pastebin.com/DYWiqhek)

I am not sure if its a bug on my side....

(replace dev.wafrn.net for app.wafrn.net)

UPDATE will try general inbox

**Comment by gabboman** [comment]
hey @MrPetovan it shoud have been fixed in the last commit. gonna leave the issue open just in case i forked up

**Comment by MrPetovan** [comment]
Thank you, I’ll post here if anything else from you pops up in my timeline.

**Comment by MrPetovan** [comment]
I have received yet another unexpected Announce from wafrn, but since it was on a conversation I participated in, I can’t be 100% sure it is unexpected: https://friendica.mrpetovan.com/display/38772fab-00b7d2c516c5cad9-d59b195b

**Comment by gabboman** [comment]
hey @MrPetovan i have updated the code that does this again butt you should not recive it. it still does the "send to public inbox" thing.

I am afraid this might be your side

**Comment by MrPetovan** [comment]
I haven't received an unexpected message from wafrn since last week, I consider this closed!
