### ISSUE TITLE
Mentions aren't displayed as mentions to other software

### ISSUE THREAD

**Issue by Freeplayg** [gabboman/wafrn-backend#14]
They're shown as regular links, preventing me from clicking on the mention to open the profile in the same home server (unless I copy & paste the 'mention' into search)
![image](https://github.com/gabboman/wafrn-backend/assets/40742947/959ffad0-cbd0-4b80-a35d-b02659ef5c84)

**Comment by gabboman** [comment]
I am aware of the issue and is on the list of things that every time i try to fix gives me a headache. will keep you updated

**Comment by gabboman** [comment]
this issue should be mostly fixed. the db is being updated slowly because we needed a new field but should be all ok
