### ISSUE TITLE
Open in original page from other software leads to a json page

### ISSUE THREAD

**Issue by Freeplayg** [gabboman/wafrn-backend#15]
Assuming backend issue ?
Open in original page on profiles is fine, posts are not
1. 
![image](https://github.com/gabboman/wafrn-backend/assets/40742947/3e25beeb-7bab-4c0a-830d-d270cf60407c)

2. 
![image](https://github.com/gabboman/wafrn-backend/assets/40742947/42bae118-46f9-4fcb-9e6e-d0807b391c45)

**Comment by gabboman** [comment]
yep, its a known issue and will be fixed this weekend if everything goes well

**Comment by Freeplayg** [comment]
This seems fixed i think
