### ISSUE TITLE
Incorrect case for signature in header

### ISSUE THREAD

**Issue by edent** [gabboman/wafrn-backend#16]
I've just received a delete message from wafrn. The headers are:

```
Accept:  application/activity+json
Content-Type:  application/activity+json
User-Agent:  app.wafrn.net
Algorithm:  rsa-sha256
Host:  example.viii.fi
Date:  Sun, 25 Feb 2024 14:53:21 GMT
Digest:  SHA-256=9akxEYDP5jC6qHvCHScxcd7zNgpkx9QTZWRsLyjHLzE=
signature:  keyId="https://app.wafrn.net/fediverse/blog/catpawsmeowmeow#main-key",algorithm="rsa-sha256",headers="(request-target) host date algorithm digest",signature="jorLnAs7phN564FE02geQS/d276TVhPn0V+cqfOHDgMklADz9PaUhGinGJmsVd4Rh9muid9hBsJIrdkbXtCMC+EHR/..="
Content-Length:  1398
Accept-Encoding:  gzip, compress, deflate, br
Connection:  keep-alive
```

By convention, all HTTP Header names are Title-Case.  I was unable to validate the signature of this message because I was looking for "**S**ignature" rather than "*s*ignature".

Every other Fediverse server uses `Signature` - so it might be worth changing?

**Comment by edent** [comment]
https://github.com/gabboman/wafrn-backend/blob/69ca199ea3ef5ad6b4a16d7c654715f703f2625b/utils/activitypub/postPetitionSigned.ts#L41

**Comment by gabboman** [comment]
I think it failed when using Signature, but will check when I arrive home

**Comment by gabboman** [comment]
masto and akkoma work. will do a test with a key fork because is here where I had some issues last time

**Comment by gabboman** [comment]
can confirm it works with the change. Fixed in git, deploying soon
