### ISSUE TITLE
I can not see other users private messages in the timeline

### ISSUE THREAD

**Issue by JuanjoSalvador** [gabboman/wafrn-backend#7]
Why?

**Comment by gabboman** [comment]
its an interesting feature, will think about it

**Comment by gabboman** [comment]
Well, speak of the devil. We actually implemented this: when you send a dm to an external user, you also could decide to send it to everyone else :D

Anyway, we have decided to remove this feature, and this is a reminder of "DO NOT BE A SMUG"
